- name: Install znc
  apt: pkg={{ item }} state=present
  with_items:
    - znc
  tags:
    - dependencies

- name: Ensure configuration folders exist
  file: state=directory path=/var/lib/znc/{{ item }} group=_znc owner=_znc
  with_items:
    - moddata
    - modules
    - users
    - configs

- name: Get a certificate from certbot
  command: certbot certonly -n --apache -d "znc.{{ domain }}"
    creates=/etc/letsencrypt/live/znc.{{ domain }}/privkey.pem

- name: Create a combined version of the SSL private key and full certificate chain
  shell: cat /etc/letsencrypt/live/znc.{{ domain }}/privkey.pem
    /etc/letsencrypt/live/znc.{{ domain }}/fullchain.pem >
    /var/lib/znc/znc.pem
    creates=/var/lib/znc/znc.pem
  notify: restart znc

- name: Ensure znc user and group can read cert
  file: path=/var/lib/znc/znc.pem group=_znc owner=_znc mode=0640
  notify: restart znc

- name: Have certbot regenerate pem file and reload znc on certificate renewal
  copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/reload-znc.sh
    content: |
      #!/bin/bash
      # Executed by /etc/cron.daily/letsencrypt-renew
      
      cat /etc/letsencrypt/live/znc.{{ domain }}/{privkey,fullchain}.pem > /var/lib/znc/znc.pem
      chown _znc._znc /var/lib/znc/znc.pem
      chmod 640 /var/lib/znc/znc.pem
      service znc restart
    owner: root
    group: root
    mode: '0755'
    backup: yes

- name: Check for existing config file
  command: cat /var/lib/znc/configs/znc.conf
  register: znc_config
  ignore_errors: True
  changed_when: False  # never report as "changed"

- name: Copy znc configuration file into place
  template: src=var_lib_znc_configs_znc.conf.j2 dest=/var/lib/znc/configs/znc.conf owner=_znc group=_znc
  when: znc_config.rc != 0
  notify: restart znc

- name: Set firewall rule for znc
  ufw: rule=allow port=6697 proto=tcp
  tags: ufw

- name: Ensure znc is a system service
  service: name=znc state=restarted enabled=true

