- import_tasks: postfix.yml
  tags: postfix
- import_tasks: database.yml
  tags: mailusers
- import_tasks: dovecot.yml
  tags: dovecot
- import_tasks: rspamd.yml
  tags: rspamd
#- include: solr.yml
#  tags: solr
#- include: checkrbl.yml
#  tags: checkrbl
#- include: z-push.yml
#  tags: zpush
- import_tasks: autoconfig.yml
  tags: autoconfig

