- name: Install Postfix and related packages
  apt: pkg={{ item }} state=present
  with_items:
    - postfix
    - postfix-pcre
    - postfix-pgsql
    - sasl2-bin
    - libsasl2-modules
#    - postgrey
# python3-psycopg2 was installed by the postgres tasks
#    - python-psycopg2
  tags:
    - dependencies

#################################################################################
# Database setup                                                                #
#################################################################################

- name: Create database user for mail server
  postgresql_user: login_host=localhost login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ mail_db_username }} password="{{ mail_db_password }}" encrypted=yes state=present
  notify: import sql postfix

- name: Create database for mail server
  postgresql_db: login_host=localhost login_user={{ db_admin_username }} login_password="{{ db_admin_password }}" name={{ mail_db_database }} state=present owner={{ mail_db_username }}
  notify: import sql postfix

# TODO: Fix reporting changed every time because of hashed password change
- name: Set up database
  copy:
    dest: /etc/postfix/import.sql
    content: |
      -- If tables are not dropped, have to truncate before insert or use "insert or replace" (not postgres compatible)
      
      DROP TABLE IF EXISTS "virtual_users";
      DROP TABLE IF EXISTS "virtual_aliases";
      DROP TABLE IF EXISTS "virtual_domains";
      
      CREATE TABLE IF NOT EXISTS "virtual_domains" (
              "id" SERIAL,
              "name" TEXT NOT NULL,
              PRIMARY KEY ("id")
      );

      CREATE UNIQUE INDEX name_idx ON virtual_domains (name);

      CREATE TABLE IF NOT EXISTS "virtual_users" (
              "id" SERIAL,
              "domain_id" int NOT NULL,
              "password" TEXT NOT NULL,
              "email" TEXT NOT NULL UNIQUE,
              PRIMARY KEY ("id"),
              FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
      );


      CREATE UNIQUE INDEX email_idx ON virtual_users (email);

      CREATE TABLE IF NOT EXISTS "virtual_aliases" (
              "id" SERIAL,
              "domain_id" int NOT NULL,
              "source" TEXT NOT NULL,
              "destination" TEXT NOT NULL,
              PRIMARY KEY ("id"),
              FOREIGN KEY (domain_id) REFERENCES virtual_domains(id) ON DELETE CASCADE
      );

      CREATE INDEX source_idx ON virtual_aliases (source);

      {% for virtual_domain in mail_virtual_domains %}
      INSERT INTO "virtual_domains" ("id", "name")
              VALUES ('{{ virtual_domain.pk_id }}', '{{ virtual_domain.name }}');
      {% endfor %}

      {% for virtual_user in mail_virtual_users %}
      INSERT INTO "virtual_users"  ("domain_id", "password" , "email")
              VALUES (
                      '{{ virtual_user.domain_pk_id }}',
                      '{{ virtual_user.password | doveadm_pw_hash }}',
                      '{{ virtual_user.account }}@{{ virtual_user.domain }}'
              );
      {% endfor %}

      {% if mail_virtual_aliases is defined %}
      {% for virtual_alias in mail_virtual_aliases %}
      INSERT INTO "virtual_aliases" ("domain_id", "source", "destination")
          VALUES ('{{ virtual_alias.domain_pk_id }}', '{{ virtual_alias.source }}', '{{virtual_alias.destination }}');
      {% endfor %}
      {% endif %}
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify: import sql postfix

- name: Create virtual alias maps for Postgres
  copy:
    dest: /etc/postfix/pgsql-virtual-alias-maps.cf
    content: |
      user = {{ mail_db_username }}
      password = {{ mail_db_password }}
      hosts = 127.0.0.1
      dbname = {{ mail_db_database }}
      query = SELECT destination FROM virtual_aliases WHERE source='%s'
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart postfix

- name: Create virtual mailbox maps for Postgres
  copy:
    dest: /etc/postfix/pgsql-virtual-mailbox-maps.cf
    content: |
      user = {{ mail_db_username }}
      password = {{ mail_db_password }}
      hosts = 127.0.0.1
      dbname = {{ mail_db_database }}
      query = SELECT 1 FROM virtual_users WHERE email='%s'
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart postfix

- name: Create virtual mailbox domains for Postgres
  copy:
    dest: /etc/postfix/pgsql-virtual-mailbox-domains.cf
    content: |
      user = {{ mail_db_username }}
      password = {{ mail_db_password }}
      hosts = 127.0.0.1
      dbname = {{ mail_db_database }}
      query = SELECT 1 FROM virtual_domains WHERE name='%s'
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart postfix

#################################################################################
# Get encryption certificates                                                   #
#################################################################################

- name: Get a certificate from certbot
  command: certbot certonly -n --apache -d "mail.{{ domain }}"
    creates=/etc/letsencrypt/live/mail.{{ domain }}/privkey.pem

- name: Have certbot restart postfix on certificate renewal
  copy:
    dest: /etc/letsencrypt/renewal-hooks/deploy/reload-postfix.sh
    content: |
      #!/bin/bash
      systemctl reload postfix
    owner: root
    group: root
    mode: '0755'
    backup: yes
  
- name: Generate a 2048 Diffie-Hellman key
  command: openssl dhparam -out {{ mail_dhparam_path }} 2048
    creates={{ mail_dhparam_path }}
  notify: restart postfix

- name: Set correct permissions and ownership on DH file
  file:
    path: /etc/ssl/private/dhparam2048.pem
    owner: root
    group: ssl-cert
    mode: '0640'

#################################################################################
# Configure main.cf                                                             #
#################################################################################

- name: Add general settings
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^myhostname\s*='
    line: "myhostname = {{ mail_server_hostname }}"
    state: present
  notify: restart postfix

- name: Ensure open relaying is prevented
  blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE - Open relay protection"
    prepend_newline: true
    insertafter: EOF
    block: |
      smtpd_recipient_restrictions =
          permit_mynetworks,
          permit_sasl_authenticated,
          reject_unauth_destination,
          reject_unauth_pipelining,
          reject_unauth_destination,
          reject_invalid_hostname,
          reject_non_fqdn_hostname,
          reject_non_fqdn_recipient,
          reject_unknown_recipient_domain,
          permit
      mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 {{ ' '.join(friendly_networks) }}
  notify: restart postfix

- name: Configure antispam
  blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE - Antispam"
    prepend_newline: true
    insertafter: EOF
    block: |
      smtpd_helo_required = yes
      smtpd_helo_restrictions = permit_mynetworks, reject_invalid_hostname
      smtpd_sender_restrictions = reject_unknown_address
      disable_vrfy_command = yes
      strict_rfc821_envelopes = yes
      invalid_hostname_reject_code = 554
      multi_recipient_bounce_reject_code = 554
      non_fqdn_reject_code = 554
      relay_domains_reject_code = 554
      unknown_address_reject_code = 554
      unknown_client_reject_code = 554
      unknown_hostname_reject_code = 554
      unknown_local_recipient_reject_code = 554
      unknown_relay_recipient_reject_code = 554
      unknown_virtual_alias_reject_code = 554
      unknown_virtual_mailbox_reject_code = 554
      unverified_recipient_reject_code = 554
      unverified_sender_reject_code = 554
  notify: restart postfix

- name: Set path to TLS certificate file
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtpd_tls_cert_file\s*='
    line: "smtpd_tls_cert_file = /etc/letsencrypt/live/mail.{{ domain }}/fullchain.pem"
    state: present
  notify: restart postfix

- name: Set path to TLS key file
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtpd_tls_key_file\s*='
    line: "smtpd_tls_key_file = /etc/letsencrypt/live/mail.{{ domain }}/privkey.pem"
    state: present
  notify: restart postfix

- name: Enable TLS for encryption
  blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE - TLS configuration"
    prepend_newline: true
    insertafter: EOF
    block: |
      smtpd_use_tls = yes
      smtpd_tls_security_level = may
      smtpd_tls_auth_only = yes
      smtpd_tls_received_header = yes
      smtpd_tls_mandatory_protocols=!SSLv2,!SSLv3
      smtpd_tls_protocols = !SSLv2,!SSLv3

      smtp_tls_security_level = may
      smtp_tls_note_starttls_offer = yes
      smtp_tls_mandatory_protocols=!SSLv2,!SSLv3
      smtp_tls_protocols = !SSLv2,!SSLv3
      # http://www.postfix.org/FORWARD_SECRECY_README.html
      smtp_tls_ciphers = medium
      smtpd_tls_dh1024_param_file = {{ mail_dhparam_path }}
  notify: restart postfix

- name: Create postfix maps directory
  file:
    path: /etc/postfix/maps
    state: directory
    owner: root
    group: root
  when: mail_header_privacy == 1

- name: Create smtp_header_checks.pcre
  copy:
    dest: /etc/postfix/maps/smtp_header_checks.pcre
    content: |
      /^\s*(Received: from)[^\n]*(.*)/ REPLACE $1 [127.0.0.1] (localhost [127.0.0.1])$2
      /^\s*User-Agent/        IGNORE
      /^\s*X-Enigmail/        IGNORE
      /^\s*X-Mailer/          IGNORE
      /^\s*X-Originating-IP/  IGNORE
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: mail_header_privacy == 1

- name: Configure to rewrite/strip headers
  blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE - Header rewriting"
    prepend_newline: true
    insertafter: EOF
    block: |
      smtp_header_checks = pcre:/etc/postfix/maps/smtp_header_checks.pcre
  notify: restart postfix
  when: mail_header_privacy == 1

- name: Enable postscreen
  blockinfile:
    path: /etc/postfix/main.cf
    marker: "# {mark} ANSIBLE - Postscreen configuration"
    prepend_newline: true
    insertafter: EOF
    block: |
      postscreen_access_list = permit_mynetworks
      postscreen_dnsbl_sites =
        zen.spamhaus.org*2
        spam.spamrats.com*1
        dyna.spamrats.com*1
        noptr.spamrats.com*1
      postscreen_dnsbl_threshold = 3
      postscreen_dnsbl_action = enforce
      postscreen_greet_action = enforce
  notify: restart postfix

#################################################################################
# Configure master.cf                                                           #
#################################################################################

- name: Configure services
  blockinfile:
    path: /etc/postfix/master.cf
    marker: "# {mark} ANSIBLE - Service configuration"
    prepend_newline: true
    insertafter: EOF
    block: |
      smtp       inet  n       -       -       -       1       postscreen
      smtpd      pass  -       -       -       -       -       smtpd
      dnsblog    unix  -       -       -       -       0       dnsblog
      tlsproxy   unix  -       -       -       -       0       tlsproxy
      submission inet  n       -       -       -       -       smtpd
        -o syslog_name=postfix/submission
        -o smtpd_tls_security_level=encrypt
        -o smtpd_etrn_restrictions=reject
        -o smtpd_client_restrictions=permit_sasl_authenticated,reject_unauth_destination,reject
        -o smtpd_sasl_security_options=noanonymous,noplaintext
        -o smtpd_sasl_tls_security_options=noanonymous
  notify: restart postfix

- name: Set firewall rules for postfix
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - smtp
    - ssmtp
    - submission
  tags: ufw
