# general
common_timezone: 'Etc/UTC'
admin_email: "{{ main_user_name }}@{{ domain }}"
main_user_shell: "/bin/bash"
friendly_networks:
  - ""

# postgres
db_admin_password: "{{ lookup('password', secret + '/' + 'db_admin_password', length=32) }}"

# encfs
encfs_password: "{{ lookup('password', secret + '/' + 'encfs_password', length=32) }}"

# ssh
kex_algorithms: "diffie-hellman-group-exchange-sha256"
ciphers: "aes256-ctr,aes192-ctr,aes128-ctr"
macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
