- name: Get a certificate from certbot
  command: certbot certonly -n --apache -d "www.{{ domain }}"
  args:
    creates: /etc/letsencrypt/live/www.{{ domain }}/privkey.pem

- name: Create directory for blog HTML
  file:
    state: directory
    path: /var/www/{{ domain }}
    group: www-data
    owner: "{{ main_user_name }}"
    mode: '0755'

- name: Remove default Apache virtualhost symlink
  file:
    state: absent
    path: /etc/apache2/sites-enabled/000-default-le-ssl.conf

- name: Configure the Apache HTTP server for the blog
  template:
    src: etc_apache2_sites-available_blog.j2
    dest: /etc/apache2/sites-available/{{ domain }}.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable blog site via symlink
  file:
    state: link
    src: /etc/apache2/sites-available/{{ domain }}.conf
    dest: /etc/apache2/sites-enabled/{{ domain }}.conf
  notify: restart apache2

- name: Validate Apache configuration
  command: apache2ctl configtest
  changed_when: false

