- name: Create gitolite group
  group: name=git state=present

- name: Create gitolite user
  user: name=git state=present home=/home/git system=yes group=git

- name: Add www-data to the git group
  user: name=www-data groups=git append=yes

- name: Install gitolite3 package
  apt: pkg=gitolite3 state=present
  tags:
    - dependencies

- name: Copy SSH public key to server
  copy: src=gitolite.pub
        dest=/home/git/{{ main_user_name }}.pub
        group=git
        owner=git
        mode=0644

- name: Setup gitolite
  become_user: git
  command: gitolite setup -pk {{ main_user_name }}.pub
           chdir=/home/git

- name: Update git config keys for gitweb
  lineinfile:
    path: /home/git/.gitolite.rc
    regexp: '^\s*GIT_CONFIG_KEYS'
    line: "    GIT_CONFIG_KEYS                 =>  'gitweb\\.(owner|description|category)',"
    state: present

- name: Get a certificate from certbot
  command: certbot certonly -n --apache -d "git.{{ domain }}"
    creates=/etc/letsencrypt/live/git.{{ domain }}/privkey.pem

