- name: Install LetsEncrypt
  apt: pkg={{ item }} state=present
  with_items:
    - snapd
  tags:
    - dependencies

- name: Ensure snapd is installed
  snap: name=snapd state=present

- name: Create symlink to ensure certbot is accessible
  file: src=/snap/bin/certbot dest=/usr/bin/certbot state=link

- name: Install certbot DNS plugin to automate generation of wildcard certificate
  snap:
    name: certbot-dns-multi
    state: present

- name: Install certbot
  snap:
    name: certbot
    state: present
    options:
    - trust-plugin-with-root=ok

- name: Connect the DNS plugin to certbot
  command: snap connect certbot:plugin certbot-dns-multi

# Here's a version for noninteractive (automated, non-manual)
certbot run -v -n -m "{user}@{domain}" --no-eff-email -agree-tos -i apache -a dns-multi --dns-multi-credentials /etc/letsencrypt/dns-multi.ini -d "*.{domain}" -d "{domain}"

certbot run -v -m "{user}@{domain}" -i apache -a dns-multi --dns-multi-credentials /etc/letsencrypt/dns-multi.ini -d "*.{domain}" -d "{domain}"
