- name: Install security-related packages
  apt: pkg={{ item }} state=present
  with_items:
    - fail2ban
    - python3-systemd
    - whois
    - lynis
    - rkhunter
  tags:
    - dependencies

- name: Copy fail2ban configuration into place
  template: src=etc_fail2ban_jail.local.j2 dest=/etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Ensure fail2ban is started
  service: name=fail2ban state=started

- name: Update sshd config
  blockinfile:
    path: /etc/ssh/sshd_config
    insertbefore: \Z
    prepend_newline: true
    append_newline: true
    block: |
      LoginGraceTime 2m
      PermitRootLogin no
      StrictModes yes
      KexAlgorithms {{ kex_algorithms }}
      Ciphers {{ ciphers }}
      MACs {{ macs }}
  notify: restart ssh

- name: Update ssh config with how to get to github
  blockinfile:
    path: /etc/ssh/ssh_config
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR GITHUB"
    insertbefore: ^Host\s\*
    prepend_newline: true
    append_newline: true
    block: |
      Host github.com
        KexAlgorithms {{ kex_algorithms }},diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1

- name: Update ssh config for defaults
  blockinfile:
    path: /etc/ssh/ssh_config
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR DEFAULT"
    insertbefore: \Z
    prepend_newline: true
    block: |
      Host *
        Ciphers {{ ciphers }}
        KexAlgorithms {{ kex_algorithms }}
